# Generated by Django 3.2.2 on 2021-05-13 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('time_food_consumed', models.DateTimeField(auto_now_add=True)),
                ('serving_size', models.IntegerField(max_length=3)),
                ('calories', models.IntegerField(max_length=20)),
                ('total_fat', models.IntegerField(max_length=20)),
                ('saturated_fat', models.IntegerField(max_length=20)),
                ('cholesterol', models.IntegerField(max_length=20)),
                ('sodium', models.IntegerField(max_length=20)),
                ('carbonhydrates', models.IntegerField(max_length=20)),
                ('fiber', models.IntegerField(max_length=20)),
                ('sugar', models.IntegerField(max_length=20)),
                ('protein', models.IntegerField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
