# Generated by Django 3.2.2 on 2021-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyconsumtion', '0002_auto_20210513_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_consumption',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
