# Generated by Django 3.2.2 on 2021-05-17 08:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailyconsumtion', '0003_alter_daily_consumption_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_consumption',
            new_name='DailyConsumption',
        ),
    ]
