# Generated by Django 3.2.2 on 2021-05-18 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dailyconsumtion', '0004_rename_daily_consumption_dailyconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyconsumption',
            name='date_time_consumed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
