# Generated by Django 3.2.2 on 2021-05-22 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyconsumtion', '0005_dailyconsumption_date_time_consumed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='media/uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyconsumption',
            name='image_url',
        ),
        migrations.AddField(
            model_name='dailyconsumption',
            name='CapturedFood_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyconsumtion.capturedfood'),
        ),
    ]
