# Generated by Django 3.2.2 on 2021-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyconsumtion', '0006_auto_20210522_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconsumption',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='carbonhydrates',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='cholesterol',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='fiber',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='saturated_fat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='sodium',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='sugar',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='total_fat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
