# Generated by Django 3.2.2 on 2021-05-25 14:22

import dailyconsumtion.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dailyconsumtion', '0007_auto_20210522_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedfood',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capturedfood',
            name='image_url',
            field=models.ImageField(upload_to=dailyconsumtion.models.path_and_rename),
        ),
    ]
